---
- name: Установка и настройка GlusterFS
  hosts: all                     # Применяется ко всем узлам
  become: yes                    # Выполнение задач с правами root
  tasks:
    - name: Установка пакетов GlusterFS
      yum:
        name: "{{ gluster_packages }}"  # Установка пакетов из переменной
        state: present

    - name: Запуск и включение службы GlusterFS
      systemd:
        name: glusterd           # Служба GlusterFS
        state: started           # Запуск службы
        enabled: yes             # Включение автозапуска при загрузке

    - name: Создание директории для brick
      file:
        path: "{{ brick_dir }}"  # Директория для хранения данных
        state: directory         # Создание директории, если её нет
        mode: '0755'             # Права доступа

    - name: Создание точки монтирования
      file:
        path: "{{ mount_point }}"  # Точка монтирования GlusterFS-тома
        state: directory           # Создание директории, если её нет
        mode: '0755'               # Права доступа

- name: Настройка кластера GlusterFS
  hosts: manager                 # Применяется только к управляющему узлу
  become: yes                    # Выполнение задач с правами root
  tasks:
    - name: Добавление узлов в кластер (peer probe)
      gluster.gluster.gluster_peer:
        state: present
        nodes: "{{ groups['gnodes'] | difference([inventory_hostname]) }}"  # Добавляем все узлы, кроме себя

    - name: Создание тома GlusterFS
      gluster.gluster.gluster_volume:
        name: "{{ volume_name }}"  # Имя тома
        state: present             # Создание тома
        replicas: 3                # Репликация на 3 узла
        bricks: "{{ brick_dir }}"  # Директория для хранения данных
        cluster: "{{ groups['hosts'] }}"  # Узлы кластера из группы hosts
        force: true                # Принудительное создание тома
      run_once: true               # Задача выполняется только один раз
      tags: volcreate              # Тег для выборочного запуска задачи

    - name: Монтирование тома на всех узлах
      mount:
        path: "{{ mount_point }}"  # Точка монтирования
        src: "{{ inventory_hostname }}:{{ volume_name }}"  # Источник монтирования (GlusterFS-том)
        fstype: glusterfs          # Тип файловой системы
        state: mounted             # Монтирование тома
      delegate_to: "{{ item }}"    # Делегирование задачи на каждый узел
      loop: "{{ groups['hosts'] }}"  # Цикл по всем узлам из группы hosts
